language: php

php:
    - 5.3
    - 5.4

before_script:
    - wget -nc http://getcomposer.org/composer.phar
    - php composer.phar --dev install

notifications:
    email:
        - arielferrandini@gmail.com